export const GET_MOVIES = 'GET_MOVIES';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const ADD_MOVIES = 'ADD_MOVIES';
export const ADD_MOVIES_SUCCESS = 'ADD_MOVIES_SUCCESS';
export const ADD_MOVIES_ERROR = 'ADD_MOVIES_ERROR';
export const FILTER_MOVIES = 'FILTER_MOVIES';
export const SEARCH_MOVIE = 'SEARCH_MOVIE';